In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier

In [2]:
df = pd.read_csv("/run/media/darshchouhan/New Volume/ML-Algorithm/Iris.csv")

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species']=le.fit_transform(df['Species'])

In [5]:
df

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [6]:
model = AdaBoostClassifier()

class AdaBoostClassifier(
 estimator: Any = None,
 *,
 n_estimators: Int = 50,
 learning_rate: Float = 1,
 algorithm: Literal['SAMME', 'SAMME.R'] = "SAMME.R",
 random_state: Int | RandomState | None = None,
 base_estimator: Any = "deprecated"
)

An AdaBoost classifier.

An AdaBoost 1 classifier is a meta-estimator that begins by fitting a classifier on the original dataset and then fits additional copies of the classifier on the same dataset but where the weights of incorrectly classified instances are adjusted such that subsequent classifiers focus more on difficult cases.

This class implements the algorithm based on 2.

Read more in the User Guide <adaboost>.

versionadded

0.14

Parameters

estimator : object, default=None
The base estimator from which the boosted ensemble is built. Support for sample weighting is required, as well as proper classes_ and n_classes_ attributes. If None, then the base estimator is DecisionTreeClassifier initialized with max_depth=1.

versionadded

1.2 base_estimator was renamed to estimator.

n_estimators : int, default=50
The maximum number of estimators at which boosting is terminated. In case of perfect fit, the learning procedure is stopped early. Values must be in the range [1, inf).

learning_rate : float, default=1.0
Weight applied to each classifier at each boosting iteration. A higher learning rate increases the contribution of each classifier. There is a trade-off between the learning_rate and n_estimators parameters. Values must be in the range (0.0, inf).

random_state : int, RandomState instance or None, default=None
Controls the random seed given at each estimator at each boosting iteration. Thus, it is only used when estimator exposes a random_state. Pass an int for reproducible output across multiple function calls. See Glossary <random_state>.

Attributes

estimator_ : estimator
The base estimator from which the ensemble is grown.

versionadded

1.2 base_estimator_ was renamed to estimator_.

estimators_ : list of classifiers
The collection of fitted sub-estimators.

classes_ : ndarray of shape (n_classes,)
The classes labels.

n_classes_ : int
The number of classes.

estimator_weights_ : ndarray of floats
Weights for each estimator in the boosted ensemble.

estimator_errors_ : ndarray of floats
Classification error for each estimator in the boosted ensemble.

feature_importances_ : ndarray of shape (n_features,)
The impurity-based feature importances if supported by the estimator (when based on decision trees).

Warning: impurity-based feature importances can be misleading for high cardinality features (many unique values). See sklearn.inspection.permutation_importance as an alternative.

n_features_in_ : int
Number of features seen during fit.

versionadded

0.24

feature_names_in_ : ndarray of shape (n_features_in_,)
Names of features seen during fit. Defined only when X has feature names that are all strings.

versionadded

1.0

See Also

AdaBoostRegressor : An AdaBoost regressor that begins by fitting a regressor on the original dataset and then fits additional copies of
the regressor on the same dataset but where the weights of instances
are adjusted according to the error of the current prediction.

GradientBoostingClassifier : GB builds an additive model in a forward stage-wise fashion. Regression trees are fit on the negative gradient
of the binomial or multinomial deviance loss function. Binary
classification is a special case where only a single regression tree is
induced.

sklearn.tree.DecisionTreeClassifier : A non-parametric supervised learning method used for classification.
Creates a model that predicts the value of a target variable by
learning simple decision rules inferred from the data features.

References

[1]: Y. Freund, R. Schapire, "A Decision-Theoretic Generalization of on-Line Learning and an Application to Boosting", 1995.

[2]: J. Zhu, H. Zou, S. Rosset, T. Hastie, "Multi-class adaboost." Statistics and its Interface 2.3 (2009): 349-360. <10.4310/SII.2009.v2.n3.a8>

Examples
>>> from sklearn.ensemble import AdaBoostClassifier
>>> from sklearn.datasets import make_classification
>>> X, y = make_classification(n_samples=1000, n_features=4,
... n_informative=2, n_redundant=0,
... random_state=0, shuffle=False)
>>> clf = AdaBoostClassifier(n_estimators=100, random_state=0)
>>> clf.fit(X, y)
AdaBoostClassifier(n_estimators=100, random_state=0)
>>> clf.predict([[0, 0, 0, 0]])
array([1])
>>> clf.score(X, y)
0.96

For a detailed example of using AdaBoost to fit a sequence of DecisionTrees as weaklearners, please refer to sphx_glr_auto_examples_ensemble_plot_adaboost_multiclass.py.

For a detailed example of using AdaBoost to fit a non-linearly separable classification dataset composed of two Gaussian quantiles clusters, please refer to sphx_glr_auto_examples_ensemble_plot_adaboost_twoclass.py.

In [7]:
X = df.drop('Species',axis=1)
y = df['Species']

In [8]:
from sklearn.model_selection import train_test_split,GridSearchCV
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.25)

In [9]:
model.fit(X_train,y_train)

AdaBoostClassifier()

In [10]:
from sklearn.metrics import accuracy_score
response=model.predict(X_test)
print(accuracy_score(y_test,response))

1.0

In [11]:
estimator = dict()
estimator['n_estimators']=[1,5,10,50,100]
estimator['learning_rate']=[0.0001,0.02,0.2,0.7]

In [12]:
estimator

{'n_estimators': [1, 5, 10, 50, 100],
 'learning_rate': [0.0001, 0.02, 0.2, 0.7]}

In [14]:
model=GridSearchCV(estimator=AdaBoostClassifier(),param_grid=estimator)

In [15]:
model.fit(X_train,y_train)

GridSearchCV(estimator=AdaBoostClassifier(),
             param_grid={'learning_rate': [0.0001, 0.02, 0.2, 0.7],
                         'n_estimators': [1, 5, 10, 50, 100]})

In [16]:
model.best_params_

{'learning_rate': 0.02, 'n_estimators': 50}

In [17]:
model.best_score_

np.float64(0.9818181818181818)

In [18]:
model = AdaBoostClassifier()
model.fit(X_train,y_train)

AdaBoostClassifier()